version: "3"

tasks:
  default:
    desc: Build everything
    deps:
      - smtpd
      - pop3d
      - package
  smtpd:
    desc: Build smtpd
    cmds:
      - echo "Building smtpd..."
      - go build -o build/smtpd cmd/smtpd/smtpd.go
  pop3d:
    desc: Build pop3d
    cmds:
      - echo "Building pop3d..."
      - go build -o build/pop3d cmd/pop3d/pop3d.go
  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - go test ./...
  package:
    desc: Package everything
    deps: 
      - deb
      - rpm
  deb:
    desc: Build deb package
    cmds:
      - echo "Building deb package..."
      - nfpm pkg --config nfpm.yaml --packager deb --target build/ 
  rpm:
    desc: Build rpm package
    cmds:
      - echo "Building rpm package..."
      - nfpm pkg --config nfpm.yaml --packager rpm --target build/
  lintian:
    desc: Run lintian
    platforms: [linux]
    cmds:
      - echo "Running lintian..."
      - lintian build/*.deb
  clean:
    desc: Clean everything
    cmds:
      - rm -rf build
