# Listener Configuration

command = "./bin/smtpd"
args = ["-cfg", "/opt/infodancer/gomail/etc/smtpd.toml"]

[server]
server_name = "mail.example.com"

[server.listener]
ip_address = "0.0.0.0"
port = 25
max_connections = 100
idle_timeout = 300  # seconds

[server.tls]
enabled = false
cert_file = "/opt/infodancer/gomail/etc/certs/server.crt"
key_file = "/opt/infodancer/gomail/etc/certs/server.key"
require_client_cert = false
min_tls_version = "1.2"
