# POP3 Server Configuration

[server]
server_name = "mail.example.com"

[server.listener]
ip_address = "0.0.0.0"
port = 110
max_connections = 50
idle_timeout = 600  # seconds
command = "bin/pop3d"
args = ["-cfg", "etc/pop3d.toml"]


[server.tls]
enabled = false
cert_file = "etc/certs/server.crt"
key_file = "etc/certs/server.key"
require_client_cert = false
min_tls_version = "1.2"
