# POP3 Server Configuration

server_name = "mail.example.com"

[listener]
ip_address = "0.0.0.0"
port = 110
max_connections = 50
idle_timeout = 600  # seconds

[tls]
enabled = false
cert_file = "/opt/infodancer/gomail/etc/certs/server.crt"
key_file = "/opt/infodancer/gomail/etc/certs/server.key"
require_client_cert = false
min_tls_version = "1.2"
