# SMTP Server Configuration

[server]
server_name = "mail.example.com"
banner = "SMTP Server Ready"
maxsize = 10485760  # 10MB max message size
spamc = "/usr/bin/spamc"


[server.listener]
ip_address = "0.0.0.0"
port = 8025
max_connections = 100
idle_timeout = 300  # seconds
command = "bin/smtpd"
args = ["-cfg", "etc/smtpd.toml"]


[server.tls]
enabled = false
cert_file = "etc/certs/server.crt"
key_file = "etc/certs/server.key"
require_client_cert = false
min_tls_version = "1.2"
