name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Install Task
      uses: arduino/setup-task@v2
    - name: Install nfpm
      run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
    - name: Build
      run: task
    - name: Test
      run: task test
